Add offline swagger and CORS support
community-of-python/microbootstrap pull request #11
Opened 2024-08-05 19:38 UTC by insani7y

2024-08-05 19:38 UTC, insani7y commented
Closes #4

2024-08-05 19:39 UTC, insani7y commented
Closes #4

2024-08-05 20:04 UTC, vrslev requested changes

2024-08-05 20:04 UTC, vrslev commented on microbootstrap/instruments/base.py
> +    ready_condition: str = dataclasses.field(init=False)
```suggestion
    instrument_name: typing.ClassVar[str]
    ready_condition: typing.ClassVar[str]
```

2024-08-05 20:04 UTC, vrslev commented on microbootstrap/instruments/cors_instrument.py
> +    cors_exposed_headers: list[str] = pydantic.Field(default_factory=list)
Со включённым pydantic mypy плагином можно так:
```suggestion
    cors_allowed_origins: list[str] = []
    cors_allowed_methods: list[str] = []
    cors_allowed_headers: list[str] = []
    cors_exposed_headers: list[str] = []
```

2024-08-05 20:04 UTC, vrslev commented on microbootstrap/instruments/opentelemetry_instrument.py
> +    ready_condition = "Provide all necessary config parameters"
Тут можно было бы указать, что это за параметры

2024-08-05 20:04 UTC, vrslev commented on microbootstrap/settings.py
> +    service_static_path: str = pydantic.Field(default="/static")
Почему не так? ну, и выше тоже

```suggestion
    service_static_path: str = "/static"
```

2024-08-05 20:04 UTC, vrslev commented on pyproject.toml
> +litestar-offline-docs = "^1.0.1"
```suggestion
litestar-offline-docs = { version = "^1.0.1", optional = true }
```

2024-08-05 20:04 UTC, vrslev commented on pyproject.toml
>  fastapi = "^0.111.0"
```suggestion
fastapi = { version = "^0.111.0", optional = true }
```

2024-08-05 20:04 UTC, vrslev commented on pyproject.toml
>  litestar = "^2.9.1"
```suggestion
litestar = { version = "^2.9.1", optional = true }
```

2024-08-05 20:04 UTC, vrslev commented on tests/conftest.py
> +def minimum_swagger_config() -> SwaggerConfig:
```suggestion
def minimal_swagger_config() -> SwaggerConfig:
```

2024-08-05 20:04 UTC, vrslev commented on tests/conftest.py
> +def minimum_cors_config() -> SwaggerConfig:
```suggestion
def minimal_cors_config() -> SwaggerConfig:
```

2024-08-05 20:04 UTC, vrslev commented on tests/conftest.py
>  def minimum_opentelemetry_config() -> OpentelemetryConfig:
```suggestion
def minimal_opentelemetry_config() -> OpentelemetryConfig:
```

2024-08-05 20:04 UTC, vrslev commented on tests/instruments/test_swagger.py
> +        assert response.status_code == status_codes.HTTP_200_OK
Как смотришь на то, чтобы использовать `http.HttpStatus`, чтобы тесты были было одинаково с тестами к бутстрапперу FastAPI, когда он будет добавлен?

2024-08-06 09:51 UTC, insani7y commented on microbootstrap/instruments/opentelemetry_instrument.py
> +    ready_condition = "Provide all necessary config parameters"
Там 5 параметров, таблица разрастется и будет уродливо

2024-08-06 09:57 UTC, insani7y commented on tests/instruments/test_swagger.py
> +        assert response.status_code == status_codes.HTTP_200_OK
Ну, статусы это же всего лишь захардкоженные инты, так что можно и лайтстаровские использовать, а можно те, что ты предложил, тут как больше нравится.  
Я бы использовал из лайстара, тк мне названия нравятся)))

2024-08-06 10:00 UTC, insani7y commented on microbootstrap/instruments/cors_instrument.py
> +    cors_exposed_headers: list[str] = pydantic.Field(default_factory=list)
Там еще ruff ругается, а гасить правило это не хочется

2024-08-06 10:34 UTC, vrslev approved these changes

2024-08-06 12:11 UTC, merged